services:
  - type: web
    name: private-cinema-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    rootDir: .

  - type: web
      name: private-cinema-frontend
      runtime: static
      buildCommand: echo "window.ENV = { SOCKET_URL: '${SOCKET_URL}' };" > env.js
      staticPublishPath: .
      branch: main
